const BAD_REQUEST = 400;

const NOT_FOUND = 404;

const SERVER_ERROR = 500;

const OK = 200;

const CREATED = 201;

const MONGO_DUPLICATE_ERROR_CODE = 11000;

const SALT = 10;

module.exports = {
  BAD_REQUEST, NOT_FOUND, SERVER_ERROR, OK, CREATED, MONGO_DUPLICATE_ERROR_CODE, SALT,
};
